### PR TITLE
Fixed issues with data sorting.

### LINKED ISSUE #41: web, data sort order newest first

### PR DESCRIPTION
**Pull request by Sirmorrison**
Fixes #41 
Sorted data from newest to oldest on exchange, PoW and VSPs

image

image

### CODE REVIEW

File: postgres/mempool.go [hunk 1]
```diff
@@ -99,7 +99,7 @@ func (pg *PgDb) BlockCount(ctx context.Context) (int64, error) {
 }
 
 func (pg *PgDb) Blocks(ctx context.Context, offset int, limit int) ([]mempool.BlockDto, error) {
-	blockSlice, err := models.Blocks(qm.OrderBy(models.BlockColumns.ReceiveTime), qm.Offset(offset), qm.Limit(limit)).All(ctx, pg.db)
+	blockSlice, err := models.Blocks(qm.OrderBy("received_time DESC"), qm.Offset(offset), qm.Limit(limit)).All(ctx, pg.db)
```
Comment (ademuanthony) [inline postgres/mempool.go]: Remove the hard-coded column name
`qm.OrderBy(fmt.Sprintf("%s DESC", models.BlockColumns.ReceiveTime)`

File: postgres/mempool.go [hunk 2]
```diff
@@ -142,7 +142,7 @@ func (pg *PgDb) SaveVote(ctx context.Context, vote mempool.Vote) error {
 }
 
 func (pg *PgDb) Votes(ctx context.Context, offset int, limit int) ([]mempool.VoteDto, error) {
-	voteSlice, err := models.Votes(qm.OrderBy(models.VoteColumns.ReceiveTime), qm.Offset(offset), qm.Limit(limit)).All(ctx, pg.db)
+	voteSlice, err := models.Votes(qm.OrderBy("received_time DESC"), qm.Offset(offset), qm.Limit(limit)).All(ctx, pg.db)
```
Comment (ademuanthony) [inline postgres/mempool.go]: Remove the hard-coded column name
```qm.OrderBy(fmt.Sprintf("%s DESC", models.BlockColumns.ReceiveTime)```

File: postgres/pow.go [hunk 3]
```diff
@@ -60,14 +60,14 @@ func responseToPowModel(data pow.PowData) (models.PowDatum, error) {
...
-		Workers:           null.IntFrom(int(data.Workers)),
+ 		Time:              int(data.Time),
+ 		Workers:           null.IntFrom(int(data.Workers)),
 	}, nil
 }
 
 // todo impliment sorting for PoW data as it is currently been sorted by time
 func (pg *PgDb) FetchPowData(ctx context.Context, offset int, limit int) ([]pow.PowDataDto, error) {
-	powDatum, err := models.PowData(qm.Offset(offset), qm.Limit(limit), qm.OrderBy("time")).All(ctx, pg.db)
+	powDatum, err := models.PowData(qm.Offset(offset), qm.Limit(limit), qm.OrderBy("time DESC")).All(ctx, pg.db)
```
Comment (ademuanthony) [inline postgres/pow.go]: Remove the hard-coded column name. See my previous comment

File: postgres/pow.go [hunk 4]
```diff
@@ -119,7 +119,7 @@ func (pg *PgDb) CountPowData(ctx context.Context) (int64, error) {
 }
 
 func (pg *PgDb) FetchPowDataBySource(ctx context.Context, source string, offset int, limit int) ([]pow.PowDataDto, error) {
-	powDatum, err := models.PowData(models.PowDatumWhere.Source.EQ(source), qm.Offset(offset), qm.Limit(limit)).All(ctx, pg.db)
+	powDatum, err := models.PowData(models.PowDatumWhere.Source.EQ(source), qm.Offset(offset), qm.Limit(limit), qm.OrderBy("time DESC")).All(ctx, pg.db)
```
Comment (ademuanthony) [inline postgres/pow.go]: Remove the hard-coded column name

File: postgres/vsp.go [hunk 5]
```diff
@@ -180,7 +180,7 @@ func (pg *PgDb) FiltredVSPTicks(ctx context.Context, vspName string, offset int,
 	}
 
 	vspIdQuery := models.VSPTickWhere.VSPID.EQ(vspInfo.ID)
-	vspTickSlice, err := models.VSPTicks(qm.Load("VSP"), vspIdQuery, qm.Limit(limit), qm.Offset(offset)).All(ctx, pg.db)
+	vspTickSlice, err := models.VSPTicks(qm.Load("VSP"), vspIdQuery, qm.Limit(limit), qm.Offset(offset), qm.OrderBy("time DESC")).All(ctx, pg.db)
```
Comment (ademuanthony) [inline postgres/vsp.go]: remove the hard-coded column name

File: postgres/vsp.go [hunk 6]
```diff
@@ -210,7 +210,7 @@ func (pg *PgDb) FiltredVSPTicks(ctx context.Context, vspName string, offset int,
 // VSPTicks
 // todo impliment sorting for VSP ticks as it is currently been sorted by time
 func (pg *PgDb) AllVSPTicks(ctx context.Context, offset int, limit int) ([]vsp.VSPTickDto, error) {
-	vspTickSlice, err := models.VSPTicks(qm.Load("VSP"), qm.Limit(limit), qm.Offset(offset), qm.OrderBy("time")).All(ctx, pg.db)
+	vspTickSlice, err := models.VSPTicks(qm.Load("VSP"), qm.Limit(limit), qm.Offset(offset), qm.OrderBy("time DESC")).All(ctx, pg.db)
```
Comment (ademuanthony) [inline postgres/vsp.go]: Remove the hard-coded column name

File: web/handlers.go [hunk 7]
```diff
@@ -31,21 +31,21 @@ func (s *Server) getExchangeTicks(res http.ResponseWriter, req *http.Request) {
...
 	allExhangeSlice, err := s.db.AllExchange(ctx)
 	if err != nil {
-			s.renderError(err.Error(), res)
-			return
-		}
+		s.renderError(err.Error(), res)
+		return
+	}
 
 	cpair, err := s.db.AllExchangeTicksCurrencyPair(ctx)
```
Comment (ademuanthony) [inline web/handlers.go]: `currencyPairs` is a better variable name

File: web/handlers.go [hunk 8]
```diff
@@ -31,21 +31,21 @@ func (s *Server) getExchangeTicks(res http.ResponseWriter, req *http.Request) {
...
 	if err != nil {
-			s.renderError(err.Error(), res)
-			return
-		}
+		s.renderError(err.Error(), res)
+		return
+	}
 
 	data := map[string]interface{}{
```
Comment (ademuanthony) [inline web/handlers.go]: Replace the key, cpair with `currencyPairs`
