### PR TITLE
Pagination fix

### LINKED ISSUE #92: exchanges table, move time column to be first on left

### PR DESCRIPTION
**Pull request by Sirmorrison**
This pr fixes #92 , #93 , #91, #83.
Also it resolves issues with next buttons hiding when there are only 2 pages to be displayed.
image

image

### CODE REVIEW

File: postgres/vsp.go [hunk 1]
```diff
@@ -148,13 +148,7 @@ func (pg *PgDb) FiltredVSPTicks(ctx context.Context, vspName string, offset int,
...
 
 	vspIdQuery := models.VSPTickWhere.VSPID.EQ(vspInfo.ID)
-
-	var vspTickSlice models.VSPTickSlice
-	if limit == 3000 {
-		vspTickSlice, err = models.VSPTicks(qm.Load("VSP"), vspIdQuery, qm.Offset(offset), qm.OrderBy(models.VSPTickColumns.Time)).All(ctx, pg.db)
-	} else {
-		vspTickSlice, err = models.VSPTicks(qm.Load("VSP"), vspIdQuery, qm.Limit(limit), qm.Offset(offset), qm.OrderBy(fmt.Sprintf("%s DESC", models.VSPTickColumns.Time))).All(ctx, pg.db)
-	}
+		vspTickSlice, err := models.VSPTicks(qm.Load("VSP"), vspIdQuery, qm.Limit(limit), qm.Offset(offset), qm.OrderBy(fmt.Sprintf("%s DESC", models.VSPTickColumns.Time))).All(ctx, pg.db)
```
Comment (ademuanthony) [inline postgres/vsp.go]: go fmt

File: web/public/app/src/controllers/pow_controller.js [hunk 2]
```diff
@@ -38,68 +37,55 @@ export default class extends Controller {
...
-    if (this.nextPage <= 1) {
-      hide(this.previousPageButtonTarget)
-    }
-    this.powTableTarget.innerHTML = ''
     this.fetchExchange(opt)
   }
 
   loadNextPage () {
     this.nextPage = this.nextPageButtonTarget.getAttribute('data-next-page')
     this.totalPages = (this.nextPageButtonTarget.getAttribute('data-total-page'))
```
Comment (ademuanthony) [inline web/public/app/src/controllers/pow_controller.js]: the total pages should come from the server as it may have been updated since the last time you checked

Comment (Sirmorrison) [reply web/public/app/src/controllers/pow_controller.js]: That line of code is not longer valid since with update i made to the PR. it take it out.

Comment (ademuanthony) [reply web/public/app/src/controllers/pow_controller.js]: I am not sure
` this.totalPages = (this.nextPageButtonTarget.getAttribute('data-total-page'))`
seems to be part of the current code base. Please confirm

Comment (Sirmorrison) [reply web/public/app/src/controllers/pow_controller.js]: `this.totalPages = (this.nextPageButtonTarget.getAttribute('data-total-page'))` 
This was used to hiding and showing the `previous` and `next` button  but the logic has been moved to lines 75.
