### PR TITLE
Modules coordination, shutdown improvement and dcrd authentication error

### LINKED ISSUE #56: fail with dcrd connection: authentication failure
Currently the app runs and succeeds with some modules and eventually gets to this.

[ERR] MEMP: Error in opening a dcrd connection: authentication failure

This should be part of a test process that runs at app startup to make sure the configuration is working properly. That way it can be detected immediately and the app will exit immediately, alerting the server administrator to the problem.

### PR DESCRIPTION
**Pull request by ademuanthony**
Removed the idle time that is noticed when a module has to wait for its cycle to complete and also fixed the shutdown delay.

image

Also fixed #56 
image

### CODE REVIEW

File: exchanges/hubs.go [hunk 1]
```diff
@@ -190,19 +189,38 @@ func (hub *TickHub) Run(ctx context.Context, wg *sync.WaitGroup) {
 		time.Sleep(timeLeft)
 	}
 
+	regiserStarter := func() {
```
Comment (Sirmorrison) [inline exchanges/hubs.go]: `regiserStarter` believe this should be `registerStarter`. If so please correct all occurrence.

File: exchanges/hubs.go [hunk 2]
```diff
@@ -190,19 +189,38 @@ func (hub *TickHub) Run(ctx context.Context, wg *sync.WaitGroup) {
...
+		for {
+			if app.MarkBusyIfFree() {
+				break
+			}
+		}
+
+		log.Info("Starting exchange tick collection cycle")
+	}
+
+	regiserStarter()
```
Comment (Sirmorrison) [inline exchanges/hubs.go]: same as above

File: exchanges/hubs.go [hunk 3]
```diff
@@ -190,19 +189,38 @@ func (hub *TickHub) Run(ctx context.Context, wg *sync.WaitGroup) {
...
 			case <-shortTicker.C:
+				regiserStarter()
 				hub.CollectShort(ctx)
+				app.ReleaseForNewModule()
 			case <-longTicker.C:
+				regiserStarter()
 				hub.CollectLong(ctx)
+				app.ReleaseForNewModule()
 			case <-dayTicker.C:
+				regiserStarter()
```
Comment (Sirmorrison) [inline exchanges/hubs.go]: same as above.

File: pow/collectors.go [hunk 4]
```diff
@@ -61,6 +63,10 @@ func NewCollector(disabledPows []string, period int64, store PowDataStore) (*Col
 	}, nil
 }
 
+func (pc *Collector) Run(ctx context.Context, wg *sync.WaitGroup) {
```
Comment (Sirmorrison) [inline pow/collectors.go]: what is this function supposed to do?

File: pow/collectors.go [hunk 5]
```diff
@@ -72,21 +78,30 @@ func (pc *Collector) CollectAsync(ctx context.Context, wg *sync.WaitGroup) {
...
 			log.Infof("Stopping PoW collectors")
 			return
+		case <-ticker.C:
+			// continually check the state of the app until its free to run this module
+			for {
+				if app.MarkBusyIfFree() {
+					break
+				}
+			}
+			log.Info("Starting a new PoW collection cycle")
```
Comment (Sirmorrison) [inline pow/collectors.go]: line space.

File: pow/collectors.go [hunk 6]
```diff
@@ -72,21 +78,30 @@ func (pc *Collector) CollectAsync(ctx context.Context, wg *sync.WaitGroup) {
...
+			pc.Collect(ctx)
+			app.ReleaseForNewModule()
 		}
```
Comment (Sirmorrison) [inline pow/collectors.go]: remove this space.
