### PR TITLE
# Added fix to make the tables and charts utilize available screen size, added some other fixes.

### LINKED ISSUE #109: removed fixed page width
Mostly is effecting charts, but may be effecting tables as well. Should utilize available screen space.

### PR DESCRIPTION
**Pull request by damiadek**
**It fixes issue #109** 

--Made the table adjust to data width and the chart to expand to fill available page space on all pages.
--Switched position of tables and charts in selector on all pages.
--Made chart default view for all pages with chart view.
--Changed order of menu items

image
image

image

image

image

--Made 1D selected by default for interval in exchanges view.

image

--Fixed typo in sample-config
image

image

### CODE REVIEW

**Comment by damiadek** [comment]
Fixes issue #109

**Comment by damiadek** [comment]
Fixes issue #109. Added fix to make the tables and charts utilize available screen size.

**Comment by raedah** [comment]
The table should not be being force to take 100% of available width. It should only use the needed width. It should not have an artificially limited width.

**Comment by damiadek** [comment]
Capture
image

**Comment by damiadek** [comment]
Switched position of tables and charts control on all pages.

Made chart default view for all pages with chart view

Made 1D selected by default for interval in exchanges view

Changed order of menu items 

image

File: web/public/app/src/controllers/exchange_controller.js [hunk 1]
```diff
@@ -23,11 +23,11 @@ export default class extends Controller {
     this.selectedFilterTarget.value = filter[0].text
     this.selectedCurrencyPairTarget.value = cpair[0].text
     this.selectedNumTarget.value = num[0].text
-    this.selectedIntervalTarget.value = interval[0].value
+    this.selectedIntervalTarget.value = interval[4].value
```
Comment (Sirmorrison) [inline web/public/app/src/controllers/exchange_controller.js]: Why did you make 1d the default view?

File: web/public/app/src/css/style.scss [hunk 2]
```diff
@@ -400,7 +405,7 @@ table.collapsible .labels tr td {
 .control-div {
   padding: 0, 0, 0, 1rem !important;
   white-space: nowrap;
-  display: inline-block;
+  // display: inline-block;
```
Comment (Sirmorrison) [inline web/public/app/src/css/style.scss]: remove commented line of code.

File: web/public/app/src/controllers/exchange_controller.js [hunk 3]
```diff
@@ -23,11 +23,11 @@ export default class extends Controller {
...
   }
 
   initialize () {
-    this.viewOption = 'table'
+    this.setChart()
```
Comment (Sirmorrison) [inline web/public/app/src/controllers/exchange_controller.js]: This would give you some major issues as you are calling up  the chart view function on initialization of the controller. If you where to call a function it should be the table function. Reason is the table view is the default view.

Again what if we choose to rename the view function from `setChart` to maybe `displayChartView`. It means we will have to rename if for every instance where it is initialize as compared to initializing `this.viewOption` where all a dev need is to choose to rename either `table` or `chart`.

so i think the change really isn't necessary.

File: web/public/app/src/controllers/mempool_controller.js [hunk 4]
```diff
@@ -26,7 +26,7 @@ export default class extends Controller {
       this.currentPage = 1
     }
     this.dataType = 'size'
-    this.viewOption = 'table'
+    this.setChart()
```
Comment (Sirmorrison) [inline web/public/app/src/controllers/mempool_controller.js]: Refer to my comment above.

File: web/public/app/src/controllers/pow_controller.js [hunk 5]
```diff
@@ -15,7 +15,7 @@ export default class extends Controller {
   }
 
   initialize () {
-    this.viewOption = 'table'
+    this.setChart()
```
Comment (Sirmorrison) [inline web/public/app/src/controllers/pow_controller.js]: Same as above.

File: web/public/app/src/controllers/vsp_controller.js [hunk 6]
```diff
@@ -28,14 +28,14 @@ export default class extends Controller {
...
     }
-    this.viewOption = 'table'
 
     this.vsps = []
     this.chartSourceTargets.forEach(chartSource => {
       if (chartSource.checked) {
         this.vsps.push(chartSource.value)
       }
     })
+    this.setChart()
```
Comment (Sirmorrison) [inline web/public/app/src/controllers/vsp_controller.js]: Same as above.

File: web/views/error.html [hunk 7]
```diff
@@ -1,15 +1,16 @@
...
-            <h3 class="text-danger mb-3">Oops</h3>
-            <div class="alert alert-danger">{{ .error }}</div>
-            <p>Refresh or <a href="/">Go Home</a></p>
+    <div class="body">
+        {{ template "header" }}
+        <div class="content">
+            <div class="container-fluid text-center">
+                <h3 class="text-danger mb-3">Oops</h3>
+                <div class="alert alert-danger">{{ .error }}</div>
+                <p>Refresh or <a href="/">Go Home</a></p>
```
Comment (Sirmorrison) [inline web/views/error.html]: Change `Go home` to `Return home`

File: web/views/error.html [hunk 8]
```diff
@@ -1,15 +1,16 @@
...
+            </div>
         </div>
     </div>
-</div>
 </body>
```
Comment (Sirmorrison) [inline web/views/error.html]: add an empty line after the `</body>` tag

File: web/views/exchange.html [hunk 9]
```diff
@@ -161,5 +170,6 @@
             </div>
         </div>
         {{ template "footer" }}
-    </body>
-    </html>
\ No newline at end of file
+</body>
+
```
Comment (Sirmorrison) [inline web/views/exchange.html]: remove empty space.

File: web/views/exchange.html [hunk 10]
```diff
@@ -161,5 +170,6 @@
...
+</html>
```
Comment (Sirmorrison) [inline web/views/exchange.html]: add an empty space after `</html>` tag

File: web/views/home.html [hunk 11]
```diff
@@ -1,14 +1,16 @@
...
         {{ template "header" }}
         <div class="content">
-            <div class="container">
+            <div class="container-fluid">
             </div>
         </div>
     </div>
     {{ template "footer" }}
 </body>
+
```
Comment (Sirmorrison) [inline web/views/home.html]: remove empty space and add it after `</html>` tag

File: web/views/layout.html [hunk 12]
```diff
@@ -8,42 +9,41 @@
...
-        <div class="container">
+        <div class="container-fluid">
             <button class="navbar-toggler" type="button" data-toggles="collapse" data-target="#nav">
                 <span class="navbar-toggler-icon"></span>
             </button>
             <div class="collapse navbar-collapse" id="nav">
-                <ul class="navbar-nav mr-auto">
+                <ul class="navbar-nav mx-auto">
                     <li class="nav-item">
-                        <a class="nav-link" id="nav-exchanges" href="/exchanges">
```
Comment (Sirmorrison) [inline web/views/layout.html]: I noticed you re-ordered the nav items was it based on instruction from @raedah or ?

File: web/views/mempool.html [hunk 13]
```diff
@@ -156,4 +149,5 @@ <h4>Mempool</h4>
     </div>
     {{ template "footer" }}
 </body>
-</html>
+
+</html>
```
Comment (Sirmorrison) [inline web/views/mempool.html]: empty line.

File: web/views/pow.html [hunk 14]
```diff
@@ -1,123 +1,120 @@
...
+            </div>
         </div>
     </div>
-</div>
-</div>
-</div>
-{{ template "footer" }}
+    {{ template "footer" }}
 </body>
+
```
Comment (Sirmorrison) [inline web/views/pow.html]: remove empty line.

File: web/views/vsp.html [hunk 15]
```diff
@@ -1,172 +1,179 @@
...
 <body>
     <div class="body" data-controller="vsp">
         {{ template "header" }}
         <div class="content">
-            <div class="container">
+            <div class="container-fluid">
                 <div class="control-wrapper">
-                    <div class="chart-control-wrapper mb-2" data-target="vsp.chartSelector">
-                        <div class="chart-control">
+                    <!-- <div class="chart-control-wrapper mb-2" data-target="vsp.chartSelector">
```
Comment (Sirmorrison) [inline web/views/vsp.html]: remove commented lines of codes.

File: web/public/app/src/controllers/exchange_controller.js (hunk 1 above)
Comment (damiadek) [reply web/public/app/src/controllers/exchange_controller.js]: It was requested by @raedah

File: web/public/app/src/controllers/exchange_controller.js (hunk 3 above)
Comment (damiadek) [reply web/public/app/src/controllers/exchange_controller.js]: The chart loading by default was also requested by @raedah . It's my bad, let me add the tasks he added to the description.


Also, setting `this.viewOption` was my first option, but, it did not have the required effect.

File: web/views/layout.html (hunk 12 above)
Comment (damiadek) [reply web/views/layout.html]: Based on instruction

File: web/public/app/src/controllers/exchange_controller.js (hunk 3 above)
Comment (damiadek) [reply web/public/app/src/controllers/exchange_controller.js]: I think it's better to reference a function than to use a string literal to modify the view option. It would give you the flexibility to switch your `setChart` and `setTable` functions incase functionalities change.

**Comment by Sirmorrison** [comment]
image

i observed that the tables are all either center aligned or occupying the entire width of the screen. Please centralize this table.

**Comment by damiadek** [comment]
@Sirmorrison ,



**--- Fixed.**
> i observed that the tables are all either center aligned or occupying the entire width of the screen. Please centralize this table.
image



**--- Fixed.**
> PoW is not displaying any data please fix it.
image



**--- This happens when the screens size is too small.**
> fix the issue with the warp on the view selector.


**--- Fixed.**
> and since everything is centralized now, i think it will be nice for every thing on the selector section to be equally spaced out.


**--- Which table has fixed width?.**
> I also noticed the tables have fixed width. From the description f what was fixed was for the tables and chart to utilize available space.

**Comment by Sirmorrison** [comment]
image

fix issue with the pagination wrap.. this was fixed some time back. the pagination should remain inline.

File: web/views/exchange.html [hunk 16]
```diff
@@ -1,103 +1,112 @@
...
         {{ template "header" }}
         <div class="content">
-            <div class="container">
+            <div class="container-fluid">
                 <div class="control-wrapper">
-                    <div class="row chart-control-wrapper mb-2" data-target="exchange.chartSelector">
-                        <div class="chart-control">
+                    <div class="d-flex flex-row bottom-ctl">
+                        <div class="chart-control ml-auto mr-2 my-2">
                             <ul class="nav nav-pills">
```
Comment (Sirmorrison) [inline web/views/exchange.html]: add `style="white-space: nowrap;`

File: web/public/app/src/controllers/pow_controller.js [hunk 17]
```diff
@@ -128,8 +128,9 @@ export default class extends Controller {
     var data = []
     var dataSet = []
     pows.forEach(pow => {
-      data.push(new Date(pow.Time))
-      data.push(pow.pool_hashrate_th)
+      pow.time = this.formatPowDateTime(pow.time)
```
Comment (Sirmorrison) [inline web/public/app/src/controllers/pow_controller.js]: Revert this to what it use to be.

File: web/public/app/src/controllers/pow_controller.js [hunk 18]
```diff
@@ -160,4 +161,10 @@ export default class extends Controller {
       }
     })
   }
+
+  formatPowDateTime (dateTime) {
```
Comment (Sirmorrison) [inline web/public/app/src/controllers/pow_controller.js]: Remove this function.
