### PR TITLE
mempool, propagation page size feature implementation And general bug fix.

### LINKED ISSUE #91: pagination text wraps incorrectly
2019-07-19 06 10 12 dcrextdata raedahgroup com 2cbccfee0939

### PR DESCRIPTION
**Pull request by Sirmorrison**
fixes #91, #65, #96 , #98 , #104

added `/` to page title, renamed VSPticks to VSP #98 
image

image

added page size  feature to mempool and propagation pages #65
image

fixed issues with table head wrap, hash label not wrapping with hash, date format #96, #91  
image

fixed issues this selector alignment. 
image

image

### CODE REVIEW

File: web/handlers.go [hunk 1]
```diff
@@ -17,14 +17,19 @@ var (
 	recordsPerPage = 20
 )
 
+// /home
+func (s *Server) getHomeData(res http.ResponseWriter, req *http.Request) {
```
Comment (ademuanthony) [inline web/handlers.go]: `homePage` is a better name

File: web/handlers.go [hunk 2]
```diff
@@ -499,17 +509,29 @@ func (s *Server) getMempool(res http.ResponseWriter, req *http.Request) {
...
+	if numberOfRows != "" {
+		numRows, err := strconv.Atoi(numberOfRows)
+		if err != nil || numRows <= 0 {
+			pageSize = pageSize
+		} else {
+			pageSize = numRows
+		}
+	}
 
 	pageToLoad, err := strconv.ParseInt(page, 10, 32)
```
Comment (ademuanthony) [inline web/handlers.go]: we can just use ` strconv.Atoi` and won't need the conversion in line 530 again

File: web/public/app/src/controllers/mempool_controller.js [hunk 3]
```diff
@@ -27,6 +33,7 @@ export default class extends Controller {
     this.setActiveOptionBtn(opt, this.viewOptionTargets)
     this.chartWrapperTarget.classList.add('d-hide')
     this.tableWrapperTarget.classList.remove('d-hide')
+    this.numPageWrapperTarget.classList.remove('d-hide')
```
Comment (ademuanthony) [inline web/public/app/src/controllers/mempool_controller.js]: please let's use the  `hide` and `show` function in the `utils` module for consistency.
` this.numPageWrapperTarget.classList.remove('d-hide')` should become `show( this.numPageWrapperTarget)` and
`this.chartWrapperTarget.classList.add('d-hide')` should become `hide(this.chartWrapperTarget)`

File: web/public/app/src/controllers/pow_controller.js [hunk 4]
```diff
@@ -15,6 +15,13 @@ export default class extends Controller {
     ]
   }
 
+  connect () {
+    var filter = this.selectedFilterTarget.options
+    var num = this.selectedNumTarget.options
+    this.selectedFilterTarget.value = filter[0].text
```
Comment (ademuanthony) [inline web/public/app/src/controllers/pow_controller.js]: you can just mark the first option as `selected` in `HTML`

File: web/public/app/src/controllers/propagation_controller.js [hunk 5]
```diff
@@ -6,13 +6,20 @@ export default class extends Controller {
...
       'table', 'blocksTbody', 'votesTbody',
       'blocksTable', 'blocksTableBody', 'blocksRowTemplate', 'votesTable', 'votesTableBody', 'votesRowTemplate',
       'totalPageCount', 'currentPage'
     ]
   }
 
+  connect () {
+    var filter = this.selectedRecordSetTarget.options
+    var num = this.selectedNumTarget.options
+    this.selectedRecordSetTarget.value = filter[0].value
```
Comment (ademuanthony) [inline web/public/app/src/controllers/propagation_controller.js]: we can just mark the first option is `selected` in `HTML`

File: web/public/app/src/controllers/propagation_controller.js [hunk 6]
```diff
@@ -35,8 +42,15 @@ export default class extends Controller {
     this.fetchData(this.currentPage + 1)
   }
 
+  NumberOfRowsChanged () {
```
Comment (ademuanthony) [inline web/public/app/src/controllers/propagation_controller.js]: `numberOfRowsChanged`

File: web/server.go [hunk 7]
```diff
@@ -106,10 +106,11 @@ func FileServer(r chi.Router, path string, root http.FileSystem) {
 }
 
 func (s *Server) registerHandlers(r *chi.Mux) {
-	r.Get("/", s.getExchangeTicks)
+	r.Get("/", s.getHomeData)
```
Comment (ademuanthony) [inline web/server.go]: `r.Get("/", s.getHomeData)` become `r.Get("/", s.homePage)`
See my previous comment

File: web/views/exchange.html [hunk 8]
```diff
@@ -34,10 +34,11 @@
                     </div>
 
                     <div class="row align-items-center justify-content-between">
-                    <div data-target=exchange.sourceWrapper class="col-md-3 control-div">
+                        <div data-target=exchange.sourceWrapper class="col-md-3 control-div pr-0">
                             <div class="control-label">Source:</div>
                             <select data-target="exchange.selectedFilter" data-action="change->exchange#selectedFilterChanged"
                                 class="form-control" style="width: 110px;">
+                                {{$selectedFilter := .selectedFilter}}
                                 <option value="All">All</option>
```
Comment (ademuanthony) [inline web/views/exchange.html]: `<option value="All">All</option>` becomes `<option value="All" selected>All</option>`
see my previous comment

File: web/views/exchange.html [hunk 9]
```diff
@@ -34,10 +34,11 @@
                     </div>
 
                     <div class="row align-items-center justify-content-between">
-                    <div data-target=exchange.sourceWrapper class="col-md-3 control-div">
+                        <div data-target=exchange.sourceWrapper class="col-md-3 control-div pr-0">
                             <div class="control-label">Source:</div>
                             <select data-target="exchange.selectedFilter" data-action="change->exchange#selectedFilterChanged"
                                 class="form-control" style="width: 110px;">
+                                {{$selectedFilter := .selectedFilter}}
```
Comment (ademuanthony) [inline web/views/exchange.html]: remove unused variable

File: web/views/exchange.html [hunk 10]
```diff
@@ -48,6 +49,7 @@
                             <div class="control-label">Currency Pair:</div>
                             <select data-target="exchange.selectedCpair" data-action="change->exchange#selectedCpairChanged"
                                 class="form-control" style="width: 110px;">
+                                {{$selectedCpair := .selectedCpair}}                         
                                 <option data-target="exchange.hideOption value="All">All</option>
```
Comment (ademuanthony) [inline web/views/exchange.html]: `<option data-target="exchange.hideOption value="All">All</option>` should be `<option data-target="exchange.hideOption" value="All">All</option>`.
Note the closing `"` if the `data-target' attribute

File: web/views/exchange.html [hunk 11]
```diff
@@ -81,6 +83,7 @@
                             <div class="control-label">Page Size:</div>
 
                             <select data-target="exchange.selectedNum" data-action="change->exchange#NumberOfRowsChanged" class="form-control" style="width: 70px;">
+                                {{$selectedNum := .selectedNum}}
```
Comment (ademuanthony) [inline web/views/exchange.html]: remove used variable
